---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r echo=T}
  #install.packages("SportsAnalytics")
  library(SportsAnalytics)
  NBA1415<-fetch_NBAPlayerStatistics("14-15")

```

##各隊最辛苦的球員
計算依據為出戰分鐘數最多的球員

```{r echo=T}
MaxMinutesPlayed<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
NBA1415MaxMinutesPlayed<-merge(NBA1415,MaxMinutesPlayed)
output<-NBA1415MaxMinutesPlayed[order(NBA1415MaxMinutesPlayed$TotalMinutesPlayed,decreasing = T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digits = 2)

```

##各隊得分王
計算依據為全季總得分最多的球員

```{r echo=T}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digits = 2)

```

##各隊最有效率的球員
總得分/出戰分鐘數 最高的球員

```{r echo=T}
MostEfficiency<-aggregate(TotalPoints/TotalMinutesPlayed ~Team+Name+TotalPoints+TotalMinutesPlayed,NBA1415,max)
names(MostEfficiency)<- c("Team","Name","TotalPoints","TotalMinutesPlayed","Efficiency")
TheMostEfficiency<-aggregate(Efficiency~Team,MostEfficiency,max)
NBA1415MostEfficiency<-merge(MostEfficiency,TheMostEfficiency)
output<-NBA1415MostEfficiency[order(NBA1415MostEfficiency$Efficiency,decreasing = T),c("Team","Name","Efficiency")]
library(knitr)
kable(output, digits = 2)

```

##各隊三分球出手最準的球員
三分球得分數/三分球出手數 最高的球員

```{r echo=T}
ThreesMadeAccuracy<-aggregate(ThreesMade/ThreesAttempted~Team+Name+ThreesMade+ThreesAttempted,NBA1415,max)
names(ThreesMadeAccuracy)<- c("Team","Name","ThreesMade","ThreesAttempted","Accuracy")
MostThreesMadeAccuracy<-aggregate(Accuracy~Team,ThreesMadeAccuracy,max)
NBA1415ThreesMadeAccuracy<-merge(ThreesMadeAccuracy,MostThreesMadeAccuracy)
output<-NBA1415ThreesMadeAccuracy[order(NBA1415ThreesMadeAccuracy$Accuracy,decreasing = T),c("Team","Name","Accuracy")]
library(knitr)
kable(output, digits = 2)

```
